---

- hosts: zookeeper
  remote_user: vagrant
  become: yes
  roles:
    - zookeeper

- hosts: master
  remote_user: vagrant
  become: yes
  roles:
    - mesos

- hosts: slave
  remote_user: vagrant
  become: yes
  roles:
    - docker
    - mesos
