---

- name: MESOS DEBIAN | Install prerequisites packages
  apt:
    name:
      - wget
      - curl
      - unzip
      - python-setuptools
      - python-dev
    state: present

- name: MESOS DEBIAN | Add repository key
  apt_key:
    id: E56151BF
    keyserver: "{{ mesos_apt_repository_key }}"
    state: present

- name: MESOS DEBIAN | Add repository
  apt_repository:
    repo: "{{ mesos_apt_repository_url }}"
    update_cache: true
    state: present
