---

mesosphere_apt_url: "http://repos.mesosphere.com/ubuntu"

mesos_cluster_name: "mesos_cluster"
# mesos_ip: "{{ ansible_default_ipv4.address }}"
mesos_ip: "{{ inventory_hostname }}"
mesos_hostname: "{{ ansible_hostname }}"
mesos_master_port: "5050"
mesos_slave_port: "5051"
mesos_log_location: "/var/log/mesos"
mesos_ulimit: "-n 8192"
mesos_work_dir: "/opt/mesos"
mesos_quorum: "1"
zookeeper_client_port: "2181"
zookeeper_hostnames: "{{ groups['master'][0] }}:{{ zookeeper_client_port }}"
mesos_zookeeper_masters: "zk://{{ zookeeper_hostnames }}/mesos"
mesos_owner: root
mesos_group: root

mesos_containerizers: "docker,mesos"
mesos_executor_timeout: "5mins"

mesos_ssl_enabled: false
mesos_ssl_support_downgrade: false

mesos_agent_meta_cleanup: false

mesos_option_prefix: "MESOS_"

# Additional configurations
mesos_additional_configs: []
  # For example:
  # - name: FOO
  #   value: bar

# Additional configurations for master
mesos_master_additional_configs: []
  # For example:
  # - name: FOO
  #   value: bar

# Additional configurations for slave
mesos_slave_additional_configs: []
  # For example:
  # - name: FOO
#   value: bar
